[package]
name = "arcoder"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"

[[bin]]
name = "encode"
path = "src/bin/encode.rs"

[[bin]]
name = "decode"
path = "src/bin/decode.rs"
